apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tailzero-connector.generatedRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tailzero-connector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tailzero-connector.generatedServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "tailzero-connector.generatedRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
